### ISSUE TITLE
2/2) ErrorException Trying to get property of non-object (View: /var/www/html/..../resources/views/nearby/index.blade.php)

### ISSUE THREAD

**Issue by tuayo77** [lvntayn/laravel-social-network#1]
am getting this error can please somme one help me ??

**2/2) ErrorException Trying to get property of non-object (View: /var/www/html/..../resources/views/nearby/index.blade.php)**

**Comment by lvntayn** [comment]
Could you write the entire error?

**Comment by tuayo77** [comment]
The project is not secured and google blocks the unsecured access that is my problem and thank you for listening
