### ISSUE TITLE
Server Access problem

### ISSUE THREAD

**Issue by tuayo77** [lvntayn/laravel-social-network#2]
**I have given permission to read write and execute to the public folder and has all the other subfolder but I can not manage to post an image on the server
Only the text leaves
Need help please**

**Comment by lvntayn** [comment]
Can you execute " php artisan storage:link " this command ?

**Comment by tuayo77** [comment]
I have already done and it returns me that the file has already been created

**Comment by lvntayn** [comment]
I can't understand problem sorry. Could you please give me detail and screenshoot ?

**Comment by tuayo77** [comment]
i receive a modal whish the text "some things wrong"

**Comment by tuayo77** [comment]
you have the same probleme in your web site chek it please

**Comment by joseseie** [comment]
@tuayo77 I think thank it's fixed know. I tested online it seems that fixed.

**Comment by toyeebgodo** [comment]
on running php artisan serve after following the installation instructions, I added several hobbies to my profile. I expected to find myself in those corresponding groups, however, I keep getting the message "You are not in any group."

@tuayo77  and @joseseie, can any one of you help me, please (https://github.com/lvntayn/laravel-social-network/issues/9 )?.
