### ISSUE TITLE
contact user message ?

### ISSUE THREAD

**Issue by SarajevoNo1** [lvntayn/laravel-social-network#5]
Hi how can I contact users on laravel social network I dont see the send message button ?

thanks

**Comment by SarajevoNo1** [comment]
where is the admin dashboard to manage users etc... ?

**Comment by lvntayn** [comment]
You can send message on messages pages where found in left menu. 

I'm sorry there is no admin dashboard because i developed this project for my database course in university. Then, we didn't panel. You can develop easily if you know laravel.

**Comment by SarajevoNo1** [comment]
Can u implemeny admin dashboard for me...

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
